# Generated by Django 3.2 on 2022-04-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='lga_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ward',
            name='ward_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
