# Generated by Django 3.2 on 2022-04-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20220405_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollingunit',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pollingunit',
            name='polling_unit_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
