# Generated by Django 3.2 on 2022-04-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20220405_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
