# Generated by Django 3.2 on 2022-04-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_alter_ward_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=80),
        ),
        migrations.AlterField(
            model_name='agent',
            name='first_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='agent',
            name='last_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='party',
            name='abbreviation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='entered_by',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
